# Generated by Django 5.1.2 on 2024-12-11 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='numero',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
