# Generated by Django 5.1.2 on 2024-12-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0003_remove_habitacion_disponible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='direccion',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
