# Generated by Django 5.1.2 on 2024-12-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arriendos', '0004_habitacion_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='total_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
